"""Scale every family up, with more variance, and add psychometric items.

What changes:
  NAMES     12 -> 40 for derivation, plus 8 HELD-OUT names never used in any
            derivation (including Ana) so injection targets can be tested
            out-of-distribution deliberately rather than by accident.
  items     each hand-written family: template x 40 names x 12 settings x 4
            paraphrases of the template (model-generated, checked) -> up to 640
            distinct items; built with n=192 per family by default.
  ipip      RELABELED after review: IPIP trust-facet items describe a person who
            TRUSTS (the perceiver's disposition), not a person who IS TRUSTWORTHY
            (the target). Kept as a DISPOSITION CONTROL — the question it answers is
            whether "n trusts people" and "n is trustworthy" are different directions.
  benev     a NEW family for the target-side gap: Mayer-Davis-style BENEVOLENCE
            (does {n} care about your interests), the one trustworthiness component
            our competence/honesty/reliability controls do not cover.
  prior     64 facts x 40 source pairs (mostly generic low-credibility sources).
  stories   already scaled to 64 per cell by the running job.

Paraphrases are generated by the model, then gated: must contain {n}, must not
flip polarity (checked by asking the model to classify the paraphrase's polarity),
must stay within 2x template length.
"""
import json, os, sys, re
import torch
_HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, _HERE)
from common import load

OUT = os.environ.get("OUT", os.path.join(_HERE, "..", "out"))

NAMES_TRAIN = [
    "Bob", "Mira", "Petrov", "Tessa", "Jonas", "Riku", "Dana", "Wen", "Alice",
    "Kai", "Nadia", "Omar", "Priya", "Marcus", "Yuki", "Fatima", "Diego",
    "Ingrid", "Kwame", "Leila", "Stefan", "Amara", "Chen", "Rosa", "Viktor",
    "Aisha", "Tomas", "Zainab", "Henrik", "Mei", "Kofi", "Elena", "Raj",
    "Sofia", "Emeka", "Hana", "Lars", "Yasmin", "Piotr", "Noor",
]
NAMES_HELDOUT = ["Ana", "Bruno", "Greta", "Sami", "Idris", "Paula", "Kenji", "Vera"]

IPIP_TRUST = [
    ("{n} believes that others have good intentions.",
     "{n} suspects hidden motives in others."),
    ("{n} trusts what people say.", "{n} distrusts what people say."),
    ("{n} believes that people are basically moral.",
     "{n} believes that people are out for their own gain."),
    ("{n} thinks the best of people until proven wrong.",
     "{n} assumes the worst of people until proven wrong."),
    ("{n} takes people at their word.", "{n} doubts people's word as a rule."),
    ("{n} is easy to win the confidence of.", "{n} is wary of everyone by default."),
    ("Colleagues describe {n} as someone who gives others the benefit of the doubt.",
     "Colleagues describe {n} as someone who gives no one the benefit of the doubt."),
    ("{n} lends things without worrying about getting them back.",
     "{n} will not lend anything for fear of never getting it back."),
]

# Verified against Mayer & Davis (1999, J. Applied Psychology 84(1), appendix, p.136).
# Adapted minimally: third person about {n}; "top management" -> the person; negatives
# constructed as direct negations since the instrument uses Likert disagreement.
ABI_BENEVOLENCE = [
    ("{n} is very concerned about your welfare.",
     "{n} is not at all concerned about your welfare."),
    ("Your needs and desires are very important to {n}.",
     "Your needs and desires do not matter to {n}."),
    ("{n} would not knowingly do anything to hurt you.",
     "{n} would knowingly hurt you if it served {n}."),
    ("{n} really looks out for what is important to you.",
     "{n} ignores what is important to you."),
    ("{n} will go out of the way to help you.",
     "{n} will not lift a finger to help you."),
]
ABI_TRUST_BEHAV = [
    ("You would be willing to let {n} have complete control over your future here.",
     "You would never let {n} have any control over your future here."),
    ("You would be comfortable giving {n} a task critical to you, even if you "
     "could not monitor what {n} did.",
     "You would not give {n} any task critical to you unless you could watch "
     "every step."),
    ("You feel no need to keep an eye on {n}.",
     "You really wish you had a good way to keep an eye on {n}."),
    ("You would let {n} act on your behalf without checking up.",
     "You check up on everything {n} does on your behalf."),
]
ABI_PROPENSITY = [
    ("{n} believes most people can be counted on to do what they say they will do.",
     "{n} believes you must stay alert or someone will take advantage of you."),
    ("{n} thinks most salespeople are honest in describing their products.",
     "{n} thinks salespeople will say anything to make a sale."),
    ("{n} believes most experts tell the truth about the limits of their knowledge.",
     "{n} believes most experts overstate what they know."),
    ("{n} takes strangers as basically decent until shown otherwise.",
     "{n} treats every stranger with great caution."),
]
BENEV = ABI_BENEVOLENCE

PARA_PROMPT = ("Rewrite the following sentence four different ways, keeping the "
               "meaning exactly, keeping the placeholder {n} exactly as written, one "
               "rewrite per line, nothing else:\n\n")

# The validated items define each construct; the model widens the item pool. Each
# generated pair must be about the DEFINED construct and nothing adjacent -- the
# definition line and the exclusions do that work, the anchors show the format.
CONSTRUCTS = {
    "benev": ("whether {n} genuinely cares about your interests and wellbeing "
              "(not whether {n} is skilled, honest, or punctual)", "ABI_BENEVOLENCE"),
    "trustbehav": ("whether you would willingly expose yourself to risk on {n}'s "
                   "account -- handing over control, going unmonitored (not whether "
                   "{n} is likeable or capable)", "ABI_TRUST_BEHAV"),
    "propensity": ("whether {n} is by disposition inclined to trust other people in "
                   "general (not whether {n} is trustworthy)", "ABI_PROPENSITY"),
}
ITEM_PROMPT = ("Here are example statement pairs about {what}. Each pair is one "
               "positive and one negative statement, using the placeholder {{n}} "
               "exactly as written.\n\n{examples}\n\nWrite {k} NEW pairs about the "
               "same thing, in the same format: positive statement, then ' ||| ', "
               "then the matching negative statement, one pair per line, nothing "
               "else. Do not reuse the examples' wording.")


def new_items(model, tok, construct, anchors, k=24):
    ex = "\n".join(f"{p} ||| {n}" for p, n in anchors[:3])
    got, tries = [], 0
    while len(got) < k and tries < 4:
        tries += 1
        for line in gen(model, tok,
                        ITEM_PROMPT.format(what=construct, examples=ex, k=k),
                        max_new=1200).split("\n"):
            if " ||| " not in line:
                continue
            pos, neg = (x.strip() for x in line.split(" ||| ", 1))
            if "{n}" in pos and "{n}" in neg and 20 < len(pos) < 200                     and 20 < len(neg) < 200 and (pos, neg) not in got:
                got.append((pos, neg))
    return got[:k]


@torch.no_grad()
def gen(model, tok, user, max_new=200):
    msgs = [{"role": "system", "content": "You are a careful writer."},
            {"role": "user", "content": user}]
    try:
        t = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True,
                                    enable_thinking=False)
    except TypeError:
        t = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
    enc = tok(t, return_tensors="pt").to(model.device)
    o = model.generate(**enc, max_new_tokens=max_new, do_sample=True, temperature=0.9,
                       top_p=0.95, pad_token_id=tok.eos_token_id)
    return tok.decode(o[0, enc["input_ids"].shape[1]:], skip_special_tokens=True)


def paraphrases(model, tok, template, k=4):
    got, tries = [template], 0
    while len(got) < k + 1 and tries < 3:
        tries += 1
        for line in gen(model, tok, PARA_PROMPT + template).split("\n"):
            line = re.sub(r"^\s*\d+[.)]\s*", "", line).strip()
            if ("{n}" in line and 0.4 < len(line) / max(1, len(template)) < 2.2
                    and line not in got):
                got.append(line)
    return got[: k + 1]


def main():
    import stimuli2 as S2
    model, tok, _ = load(); model.eval()
    bank = {"names_train": NAMES_TRAIN, "names_heldout": NAMES_HELDOUT,
            "ipip": IPIP_TRUST, "benev": BENEV, "trustbehav": ABI_TRUST_BEHAV,
            "propensity": ABI_PROPENSITY, "paraphrases": {}}
    # paraphrase every clause template in the hand-written families + ipip
    todo = {}
    for dim, (p, _, n) in S2._BARE.items():
        todo[f"bare_{dim}_pos"], todo[f"bare_{dim}_neg"] = p, n
    for dim, (p, _, n) in S2._RICH.items():
        todo[f"rich_{dim}_pos"], todo[f"rich_{dim}_neg"] = p, n
    for i, (p, n) in enumerate(IPIP_TRUST):
        todo[f"ipip_{i}_pos"], todo[f"ipip_{i}_neg"] = p, n
    for i, (p, n) in enumerate(BENEV):
        todo[f"benev_{i}_pos"], todo[f"benev_{i}_neg"] = p, n
    for i, (p, n) in enumerate(ABI_TRUST_BEHAV):
        todo[f"trustbehav_{i}_pos"], todo[f"trustbehav_{i}_neg"] = p, n
    for i, (p, n) in enumerate(ABI_PROPENSITY):
        todo[f"propensity_{i}_pos"], todo[f"propensity_{i}_neg"] = p, n
    for key, tpl in todo.items():
        bank["paraphrases"][key] = paraphrases(model, tok, tpl)
        print(f"[scale] {key}: {len(bank['paraphrases'][key])} variants", flush=True)
    # --- widen the SITUATION axes too: settings and dialogue frames -------
    SET_PROMPT = (
        "Here are examples of role settings, one per line, each as\n"
        "persona ||| referent phrase ||| relation\n\n"
        "You are a team manager at a company. ||| someone on your team ||| subordinate\n"
        "You are a junior analyst at a bank. ||| your manager ||| superior\n"
        "You are buying a used car privately. ||| the seller ||| counterparty\n\n"
        "Write 24 NEW settings in the same format, covering many walks of life and "
        "all of these relations: subordinate, peer, superior, counterparty, service "
        "provider, friend, stranger, family. One per line, nothing else.")
    got = []
    for _ in range(3):
        for line in gen(model, tok, SET_PROMPT, max_new=1200).split("\n"):
            parts = [x.strip() for x in line.split("|||")]
            if len(parts) == 3 and all(parts) and 12 < len(parts[0]) < 90 \
                    and parts not in got:
                got.append(parts)
        if len(got) >= 24:
            break
    bank["settings_generated"] = got[:24]
    print(f"[scale] settings: 12 hand-written + {len(bank['settings_generated'])} generated",
          flush=True)

    FRAME_PROMPT = (
        "Here is an example of a promise-frame, as four parts separated by ' ||| ':\n"
        "what the person commits to ||| your reply ||| the outcome line if they come "
        "through ||| the outcome line if they let you down\n\n"
        "I'll have the report to you by five today. ||| Thanks, I'm counting on it. "
        "||| Here's the report — ten to five, as promised. ||| So about the report — "
        "it's not happening today. Something came up.\n\n"
        "Write 18 NEW promise-frames in the same format, from many areas of life "
        "(money, childcare, repairs, secrets, deadlines, lifts, cover at work, "
        "borrowed things). One per line, nothing else.")
    frames = []
    for _ in range(3):
        for line in gen(model, tok, FRAME_PROMPT, max_new=1600).split("\n"):
            parts = [x.strip() for x in line.split("|||")]
            if len(parts) == 4 and all(parts) and parts not in frames:
                frames.append(parts)
        if len(frames) >= 18:
            break
    bank["frames_generated"] = frames[:18]
    print(f"[scale] dialogue frames: 6 hand-written + {len(bank['frames_generated'])} generated",
          flush=True)

    bank["generated_items"] = {}
    for cname, (definition, anchor_var) in CONSTRUCTS.items():
        anchors = {"ABI_BENEVOLENCE": ABI_BENEVOLENCE,
                   "ABI_TRUST_BEHAV": ABI_TRUST_BEHAV,
                   "ABI_PROPENSITY": ABI_PROPENSITY}[anchor_var]
        items = new_items(model, tok, definition, anchors)
        bank["generated_items"][cname] = items
        print(f"[scale] {cname}: {len(anchors)} validated anchors + "
              f"{len(items)} model-written items", flush=True)
    json.dump(bank, open(os.path.join(OUT, "scale_bank.json"), "w"), indent=1)
    print("SCALE_BANK_DONE", flush=True)


if __name__ == "__main__":
    main()
